name: Deploy Pipeline

on:
  push:
    branches: [ "main" ]

# These permissions are required for OIDC (role-to-assume) to work
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4  # Upgraded to v4 to fix warnings
        with:
          # MAKE SURE this secret name matches exactly what is in GitHub Settings > Secrets
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_YOU }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve